sudo: required
language: node_js
node_js:
  - "10.13.0"

cache:
  directories:
    - node_modules
    - ~/.npm

notifications:
  email:
    on_success: always
    on_failure: always

install:
  - echo Installing Modules...
  - npm ci

script:
  - echo Linting...
  - npm run lint
